### ISSUE TITLE
 The ch.admin.bar.siard2.api.generated package is missing.

### ISSUE THREAD

**Issue by ldev27** [sfa-siard/SiardApi#3]
It looks like the ch.admin.bar.siard2.api.generated package is missing. Please confirm.
![SiardApi_Error](https://user-images.githubusercontent.com/56239351/67615034-f4f71500-f801-11e9-94f2-f07f2b8331b4.png)

**Comment by HartwigThomas** [comment]
When you execute the build, that package is generated (hence the name) from the grammar .g4 files in /var. Thus the package is not missing. The target "generate" of the build is mentioned and described in the manual.

The same comment obtains for the project SiardApi. The generated package is generated by the build from the metadata.xsd fpr SIARD.
